import { z } from 'zod';

export const NoteSchema = z.object({
  id: z.string(),
  userId: z.string(),
  title: z.string().min(1, "Title is required"),
  content: z.string(),
  folderId: z.string().nullable().optional(),
  tags: z.array(z.string()).optional(),
  pinned: z.boolean().optional(),
  isArchived: z.boolean().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().nullable().optional(),
  syncedAt: z.string().nullable().optional(),
  _fieldUpdates: z.record(z.string(), z.string()).optional(),
}).strict();

export const TodoSchema = z.object({
  id: z.string(),
  userId: z.string(),
  title: z.string().min(1, "Title is required"),
  description: z.string().nullable().optional(),
  status: z.string().optional(),
  priority: z.enum(['low', 'medium', 'high', 'critical']).optional(),
  dueDate: z.string().nullable().optional(),
  listId: z.string().nullable().optional(),
  listName: z.string().nullable().optional(),
  tags: z.array(z.string()).optional(),
  completedAt: z.string().nullable().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().nullable().optional(),
  syncedAt: z.string().nullable().optional(),
  _fieldUpdates: z.record(z.string(), z.string()).optional(),
}).strict();

export const CalendarEventSchema = z.object({
  id: z.string(),
  userId: z.string(),
  title: z.string().min(1, "Title is required"),
  description: z.string().nullable().optional(),
  start: z.string(),
  end: z.string(),
  allDay: z.boolean().optional(),
  color: z.string().nullable().optional(),
  linkedTaskId: z.string().nullable().optional(),
  linkedNoteId: z.string().nullable().optional(),
  linkedNodeId: z.string().nullable().optional(),
  linkedWorkflowId: z.string().nullable().optional(),
  triggerFiredAt: z.string().nullable().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().nullable().optional(),
  syncedAt: z.string().nullable().optional(),
  _fieldUpdates: z.record(z.string(), z.string()).optional(),
}).strict();

export const WorkflowSchema = z.object({
  id: z.string(),
  userId: z.string(),
  title: z.string().min(1, "Title is required"),
  description: z.string().nullable().optional(),
  status: z.enum(['DRAFT', 'ACTIVE', 'ARCHIVED']).optional(),
  tags: z.array(z.string()).optional(),
  color: z.string().nullable().optional(),
  runStatus: z.string().nullable().optional(),
  lastRunAt: z.string().nullable().optional(),
  viewport: z.object({
    x: z.number(),
    y: z.number(),
    zoom: z.number(),
  }).nullable().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().nullable().optional(),
  syncedAt: z.string().nullable().optional(),
  _fieldUpdates: z.record(z.string(), z.string()).optional(),
}).strict();

export const WorkflowNodeSchema = z.object({
  id: z.string(),
  userId: z.string(),
  workflowId: z.string(),
  type: z.string(),
  label: z.string(),
  x: z.number(),
  y: z.number(),
  description: z.string().nullable().optional(),
  data: z.record(z.string(), z.any()).nullable().optional(),
  priority: z.string().optional(),
  status: z.string().optional(),
  executionState: z.string().optional(),
  dueDate: z.string().nullable().optional(),
  subtasks: z.array(z.any()).optional(),
  recurrence: z.record(z.string(), z.any()).nullable().optional(),
  progress: z.number().optional(),
  trigger: z.record(z.string(), z.any()).nullable().optional(),
  joinMode: z.string().optional(),
  executionStrategy: z.string().nullable().optional(),
  startedAt: z.string().nullable().optional(),
  completedAt: z.string().nullable().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().nullable().optional(),
  syncedAt: z.string().nullable().optional(),
  _fieldUpdates: z.record(z.string(), z.string()).optional(),
}).strict();

export const WorkflowEdgeSchema = z.object({
  id: z.string(),
  userId: z.string(),
  workflowId: z.string(),
  source: z.string(),
  target: z.string(),
  sourceHandle: z.string().nullable().optional(),
  targetHandle: z.string().nullable().optional(),
  label: z.string().nullable().optional(),
  activation: z.string().nullable().optional(),
  sourceSlot: z.number().nullable().optional(),
  targetSlot: z.number().nullable().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().nullable().optional(),
  syncedAt: z.string().nullable().optional(),
  _fieldUpdates: z.record(z.string(), z.string()).optional(),
}).strict();
